---
- hosts: all
  become: yes
  pre_tasks:

 # - name: yum update machine.
 #   yum: name='*' state=latest  

  - name: install unzip  
    yum: name='unzip' state=latest    

  - name: install tar  
    yum: name='tar' state=latest    

  roles:
   - openresty
   - nginx_files

  post_tasks:
  - name: starting nginx 
    shell: sudo openresty -c /usr/local/openresty/nginx/conf/nginx_*.conf   
