- name: copy over the resty repo.
  copy: 
    src: "OpenResty.repo"
    dest: "/etc/yum.repos.d/OpenResty.repo"
    owner: root
    group: root
    mode: "0644"

- name: install openresty.
  yum: name='openresty' state=latest     